### PR TITLE
#112 - class keyword fixer

### LINKED ISSUE #112: Codestyle wrongly assumes some strings are classes
In one of our projects Codestyle wants to change this:
```php
        if (in_array($response->status(), $this->handleByInertia, true)) {
            return Inertia::render("Error", [
                "status" => $response->status(),
            ])
                ->toResponse($request)
                ->setStatusCode($response->status());
        }
``` 
into:
```php
        if (in_array($response->status(), $this->handleByInertia, true)) {
            return Inertia::render(\Error::class, [
                "status" => $response->status(),
            ])
                ->toResponse($request)
                ->setStatusCode($response->status());
        }
```

And this makes no sense at all. Other example:

```php
            ["name" => "Redis"],
```
into:
```php
            ["name" => \Redis::class],
```

We should handle this somehow.

### PR DESCRIPTION
**Pull request by kamilpiech97**
Should close #112.

**Before:**
```
class TestException extends \Exception
{
    protected string $var = "Error";
    protected string $class = "\Error";
    protected string $laravel = "LaravelPaths";
    protected string $bar = "\PhpCsFixer\Tokenizer\Tokens";
    protected string $foo = "PhpCsFixer\Tokenizer\Tokens";
    protected string $faz = "\Tokens";

    public function rules(\Blumilk\Codestyle\Configuration\Defaults\CommonRules $rules): void
    {
        echo 123;
    }

    public function test(): void
    {
        $foo = 'Blumilk\Codestyle\Configuration\Defaults\Paths';
        $baz = "\Exception";
        $fuz = "Exception";
    }
}
```

**After:**
```
declare(strict_types=1);

use Blumilk\Codestyle\Configuration\Defaults\CommonRules;

class TestException extends Exception
{
    protected string $var = "Error";
    protected string $class = \Error::class;
    protected string $laravel = "LaravelPaths";
    protected string $bar = \PhpCsFixer\Tokenizer\Tokens::class;
    protected string $foo = \PhpCsFixer\Tokenizer\Tokens::class;
    protected string $faz = "\Tokens";

    public function rules(CommonRules $rules): void
    {
        echo 123;
    }

    public function test(): void
    {
        $foo = \Blumilk\Codestyle\Configuration\Defaults\Paths::class;
        $baz = \Exception::class;
        $fuz = "Exception";
    }
}
```

### CODE REVIEW

File: tests/fixtures/classesImport/expected.php [hunk 1]
```diff
@@ -3,14 +3,25 @@
...
 use Blumilk\Codestyle\Configuration\Defaults\CommonRules;
-use Blumilk\Codestyle\Configuration\Defaults\LaravelPaths;
 
 class TestException extends Exception
 {
-    protected string $rules = LaravelPaths::class;
+    protected string $var = "Error";
+    protected string $class = \Error::class;
+    protected string $laravel = "LaravelPaths";
+    protected string $bar = \PhpCsFixer\Tokenizer\Tokens::class;
```
Comment (krzysztofrewak) [inline tests/fixtures/classesImport/expected.php:12]: These should be imported. Maybe you could manipulate with priorities of fixers?

File: src/Fixers/ClassKeywordFixer.php [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+
+    public function supports(SplFileInfo $file): bool
+    {
+        return true;
+    }
+
+    private function exists(string $name): bool
+    {
+        if (class_exists($name) || interface_exists($name) || trait_exists($name)) {
+            $rc = new \ReflectionClass($name);
```
Comment (krzysztofrewak) [inline src/Fixers/ClassKeywordFixer.php:86]: Could you import that?

Comment (krzysztofrewak) [reply src/Fixers/ClassKeywordFixer.php:86]: And change rc to something more verbose?

File: src/Fixers/ClassKeywordFixer.php [hunk 3]
```diff
@@ -0,0 +1,93 @@
...
+    }
+
+    public function supports(SplFileInfo $file): bool
+    {
+        return true;
+    }
+
+    private function exists(string $name): bool
+    {
+        if (class_exists($name) || interface_exists($name) || trait_exists($name)) {
```
Comment (krzysztofrewak) [inline src/Fixers/ClassKeywordFixer.php:85]: What about enums?

**Review by krzysztofrewak — CHANGES_REQUESTED** [review]

File: tests/fixtures/classesImport/expected.php (hunk 1 above)
Comment (kamilpiech97) [reply tests/fixtures/classesImport/expected.php]: fixed

File: src/Fixers/ClassKeywordFixer.php (hunk 2 above)
Comment (kamilpiech97) [reply src/Fixers/ClassKeywordFixer.php]: fixed

File: src/Fixers/ClassKeywordFixer.php (hunk 3 above)
Comment (kamilpiech97) [reply src/Fixers/ClassKeywordFixer.php]: added

File: src/Fixers/ClassKeywordFixer.php [hunk 4]
```diff
@@ -72,7 +73,7 @@ public function getName(): string
 
     public function getPriority(): int
     {
-        return 0;
```
Comment (krzysztofrewak) [inline src/Fixers/ClassKeywordFixer.php]: Maybe hardcoding could be replaced with something like this? https://github.com/blumilksoftware/codestyle/blob/main/src/Fixers/NoCommentFixer.php#L69

**Review by krzysztofrewak — CHANGES_REQUESTED** [review]

File: src/Fixers/ClassKeywordFixer.php (hunk 4 above)
Comment (kamilpiech97) [reply src/Fixers/ClassKeywordFixer.php]: changed

**Review by krzysztofrewak — APPROVED** [review]

**Review by mtracz — APPROVED** [review]
